import Image from 'next/image';
import { ContactForm, Counters, Cursor, HeroVisual, Navigation, Reveal } from '@/components/Interactions';
import { projects, services, siteConfig, stack } from '@/data/config';

const Arrow=()=> <span aria-hidden="true">↗</span>;
const SectionHead=({kicker,title,copy}:{kicker:string,title:string,copy?:string})=><div className="sectionHead reveal"><span className="kicker">{kicker}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>;

export default function Home(){
 const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';
 const person={"@context":"https://schema.org","@type":"Person",name:"Karim",jobTitle:"Web Developer & Digital Product Builder",address:{"@type":"PostalAddress",addressLocality:"Patna",addressRegion:"Bihar",addressCountry:"IN"},url:siteConfig.canonicalUrl,knowsAbout:["WordPress","React","Next.js","AI integrations","SEO","Web development"]};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(person)}}/><Navigation/><Reveal/><Counters/><Cursor/>
 <main>
  <section className="hero" id="home"><div className="heroGrid"><div className="heroCopy"><div className="availability"><i/> Available for select projects</div><h1>I Build Websites, Web Apps & Digital Products <em>That Actually Work.</em></h1><p>From high-converting WordPress websites to custom SaaS platforms, AI-powered tools and business applications — I design, develop, integrate and optimize complete digital experiences.</p><div className="heroActions"><a className="button primary magnetic" href="#work">View My Work <Arrow/></a><a className="button secondary" href="#contact">Let&apos;s Work Together</a></div><div className="cred"><span>WordPress Developer</span><span>Full-Stack Builder</span><span>AI & SaaS</span><span>SEO</span></div></div><HeroVisual/></div><div className="heroFoot"><span>Based in Patna, India</span><i/><span>Working Worldwide</span><a href="#about">Scroll to explore ↓</a></div></section>

  <section className="about light" id="about"><div className="split"><SectionHead kicker="01 — About" title="More Than a Website Developer"/><div className="aboutCopy reveal"><p className="lead">I work across the complete digital product lifecycle — turning business requirements into digital products that look considered, work reliably and are ready to grow.</p><p>My work spans website design, WordPress, Elementor, WooCommerce, Shopify, PHP, JavaScript, React, Next.js, TypeScript, Firebase, APIs, AI features, SEO, performance, debugging and deployment.</p><div className="lifecycle">{['Idea','Design','Development','Integration','Optimization','Launch'].map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></div></div>
   <div className="stats">{[[50,'Websites & Digital Projects'],[2,'Years Web Development'],[6,'Months SEO Experience'],[10,'Technologies & Platforms']].map(([n,l])=><div className="stat reveal" key={l as string}><strong data-count={n}>{n}+</strong><span>{l}</span></div>)}</div>
  </section>

  <section className="services" id="services"><SectionHead kicker="02 — Capabilities" title="One Partner. Full Product Thinking." copy="Strategy, interface, code, integrations, performance and growth — connected instead of handed between silos."/><div className="serviceGrid">{services.map((s,i)=><article className="serviceCard reveal" key={s[0]}><div className="serviceTop"><span className="serviceIcon">{s[2]}</span><small>0{i+1}</small></div><h3>{s[0]}</h3><p>{s[1]}</p><span className="cardArrow">↗</span></article>)}</div></section>

  <section className="work light" id="work"><SectionHead kicker="03 — Selected Work" title="Products, Platforms & Business Websites" copy="A selection of work across SaaS, real-time applications, WordPress, healthcare and corporate digital experiences."/><div className="projectList">{projects.filter(p=>p.featured).map((p,i)=><article className="projectCard reveal" key={p.slug}><div className="projectMedia"><Image src={`${basePath}${p.image}`} alt={`${p.title} interface preview`} fill sizes="(max-width: 800px) 100vw, 55vw"/></div><div className="projectInfo"><span className="projectNo">0{i+1} / 06</span><small>{p.category}</small><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="challenge"><b>Challenge</b><p>{p.challenge}</p><b>Solution</b><p>{p.solution}</p></div><a href={p.liveUrl||`#case-${p.slug}`} target={p.liveUrl?'_blank':undefined} rel="noreferrer" className="textLink">{p.liveUrl?'Visit Project':'View Case Study'} <Arrow/></a></div></article>)}</div></section>

  <section className="case" id="case-mrooi"><SectionHead kicker="04 — How I Work" title="Not ‘I Made a Website.’ A Complete Build System."/><div className="caseRail">{[['Problem','Clarify the business need, user friction and technical constraints.'],['Strategy','Shape information architecture, responsive UX and a practical technical direction.'],['Build','Develop reusable interfaces, backend functionality, APIs and integrations.'],['Optimize','Improve performance, SEO, accessibility, usability and technical reliability.']].map((x,i)=><div className="caseStep reveal" key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></section>

  <section className="skills light" id="skills"><SectionHead kicker="05 — Technology" title="A Flexible Stack for Real-World Work" copy="The tool is never the point. I choose what fits the product, team and long-term maintenance needs."/><div className="stackGrid">{Object.entries(stack).map(([group,items])=><div className="stackGroup reveal" key={group}><h3>{group}</h3><div>{items.map(x=><span key={x}>{x}</span>)}</div></div>)}</div></section>

  <section className="philosophy"><div className="philoTitle"><span className="kicker">06 — Philosophy</span><h2>I Don&apos;t Just Make It Look Good. <em>I Make It Work.</em></h2></div><div className="pillarGrid">{[['Design','Clean interfaces built around users and business goals.'],['Development','Maintainable, responsive and functional implementations.'],['Performance','Fast loading, optimized assets and technical improvements.'],['Growth','SEO, conversion optimization and scalable functionality.']].map((x,i)=><div className="pillar reveal" key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></section>

  <section className="process light" id="process"><SectionHead kicker="07 — Process" title="From First Question to Real Users"/><div className="processLine">{[['Discover','Understand the business, audience, goals and requirements.'],['Plan','Define structure, features, content and technical approach.'],['Design','Build the visual direction and responsive experience.'],['Develop','Implement the product, APIs and integrations.'],['Launch & Optimize','Test, debug, optimize and prepare for real users.']].map((x,i)=><article className="processItem reveal" key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>

  <section className="why"><SectionHead kicker="08 — Why Karim" title="Technical Range. Business Context. No Theatre."/><div className="whyGrid">{[['Business Understanding','Features should solve real problems, not exist because they sound impressive.'],['Technical Flexibility','From WordPress and Elementor to custom applications and modern frameworks.'],['Full-Stack Thinking','Frontend, backend, APIs, databases, integrations and deployment considered together.'],['Problem Solving','Debugging difficult real-world issues is part of building dependable products.'],['Continuous Improvement','Websites should evolve through performance, SEO and UX improvements.']].map((x,i)=><div className="whyItem reveal" key={x[0]}><small>0{i+1}</small><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></section>

  <section className="story light"><div className="storyGrid"><div><span className="kicker">09 — From Websites to Products</span><h2>Built Through Curiosity, Expanded Through Practice.</h2></div><div><p>I started with web development and WordPress, then kept moving deeper — into UI/UX, SEO, custom functionality, APIs, real-time applications, AI, SaaS and automation.</p><p>That progression shapes how I work today: not as a specialist trapped in one tool, but as a product-minded developer who can connect design decisions to technical reality.</p><div className="freelance"><i/><div><b>Available for Freelance & Remote Projects</b><span>WordPress · Web Apps · AI · E-Commerce · SEO</span></div></div></div></div></section>

  <section className="contact" id="contact"><div className="contactGrid"><div className="contactCopy"><span className="kicker">10 — Contact</span><h2>Have a Project in Mind? <em>Let&apos;s Build It.</em></h2><p>Tell me what you&apos;re trying to build, improve or automate.</p><div className="contactMeta"><span><small>Based in</small>Patna, Bihar, India</span><span><small>Availability</small>Remote projects worldwide</span><span><small>Email</small>{siteConfig.email||'Add in data/config.ts'}</span></div></div><ContactForm/></div></section>

  <section className="finalCta light"><span className="kicker">Start something useful</span><h2>Let&apos;s Build Something Useful.</h2><p>Whether you need a WordPress website, custom application, AI-powered tool, e-commerce store or a complete digital product — let&apos;s turn the idea into something real.</p><div><a href="#contact" className="button primary">Start Your Project <Arrow/></a><a href="#work" className="button darkOutline">Explore My Work</a></div></section>
 </main>
 <footer><a className="footerLogo" href="#home">KARIM<span>.</span></a><p>Web Developer • Digital Product Builder</p><nav>{['Home','About','Services','Work','Skills','Contact'].map(x=><a key={x} href={x==='Home'?'#home':`#${x.toLowerCase()}`}>{x}</a>)}</nav><div className="footBottom"><span>© 2026 Karim. All rights reserved.</span><a href="#home">Back to top ↑</a></div></footer>
 </>}
