'use client';
import { useEffect, useState } from 'react';

export function Navigation(){
 const [open,setOpen]=useState(false),[compact,setCompact]=useState(false);
 useEffect(()=>{const fn=()=>setCompact(scrollY>40);addEventListener('scroll',fn,{passive:true});return()=>removeEventListener('scroll',fn)},[]);
 const links=['About','Services','Work','Skills','Process','Contact'];
 return <header className={`nav ${compact?'compact':''}`}><a className="logo" href="#home" aria-label="Karim home">KARIM<span>.</span></a><nav className={open?'open':''} aria-label="Primary navigation">{links.map(x=><a onClick={()=>setOpen(false)} key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><a className="button navCta" href="#contact">Start a Project <span>↗</span></a><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle menu"><i/><i/></button></header>
}

export function Reveal(){useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));return()=>io.disconnect()},[]);return null}

export function HeroVisual(){
 const basePath=process.env.NEXT_PUBLIC_BASE_PATH||'';
 useEffect(()=>{const el=document.querySelector('.portraitStage') as HTMLElement|null;if(!el)return;const move=(e:PointerEvent)=>{if(innerWidth<900)return;const x=(e.clientX/innerWidth-.5)*5,y=(e.clientY/innerHeight-.5)*-4;el.style.transform=`rotateY(${x}deg) rotateX(${y}deg)`};addEventListener('pointermove',move);return()=>removeEventListener('pointermove',move)},[]);
 return <div className="visual portraitVisual" aria-label="AI-created editorial portrait of Karim"><div className="portraitStage"><div className="portraitFrame"><img src={`${basePath}/karim-ai-portrait.jpg`} alt="AI-created editorial portrait representing Karim"/><div className="portraitAvailability"><i/> Available for work</div></div><div className="portraitCaption"><span>Karim</span><small>Web Developer · Patna, India</small></div></div></div>
}

export function Counters(){useEffect(()=>{const els=document.querySelectorAll<HTMLElement>('[data-count]');const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target as HTMLElement,target=Number(el.dataset.count);let n=0;const timer=setInterval(()=>{n+=Math.max(1,Math.ceil((target-n)/7));if(n>=target){n=target;clearInterval(timer)}el.textContent=n+'+'},35);io.unobserve(el)}));els.forEach(x=>io.observe(x));return()=>io.disconnect()},[]);return null}

export function ContactForm(){const [sent,setSent]=useState(false);return <form className="contactForm" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="fieldRow"><label>Name<input required name="name" autoComplete="name"/></label><label>Email<input required type="email" name="email" autoComplete="email"/></label></div><div className="fieldRow"><label>Company / Business<input name="company"/></label><label>Project Type<select name="type" defaultValue=""><option value="" disabled>Select a service</option>{['WordPress Website','Elementor Website','E-Commerce','Web Application','SaaS','AI Integration','SEO','Website Redesign','Other'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Budget<select name="budget" defaultValue=""><option value="" disabled>Select a range</option><option>₹15k–₹30k</option><option>₹30k–₹75k</option><option>₹75k–₹1.5L</option><option>₹1.5L+</option><option>Let’s discuss</option></select></label><label>Message<textarea required name="message" rows={5} placeholder="Tell me what you’re trying to build, improve or automate."/></label><button className="button primary" type="submit">{sent?'Message ready — add email in config ✓':'Start a Conversation'} <span>↗</span></button><p className="formNote">The form UI is ready. Add your email or form endpoint in <code>data/config.ts</code> before launch.</p></form>}

export function Cursor(){useEffect(()=>{if(matchMedia('(pointer:coarse)').matches)return;const c=document.createElement('div');c.className='cursor';document.body.append(c);const m=(e:PointerEvent)=>{c.style.transform=`translate(${e.clientX}px,${e.clientY}px)`};addEventListener('pointermove',m);document.querySelectorAll('a,button,.projectCard').forEach(el=>{el.addEventListener('mouseenter',()=>c.classList.add('active'));el.addEventListener('mouseleave',()=>c.classList.remove('active'))});return()=>{removeEventListener('pointermove',m);c.remove()}},[]);return null}